### ISSUE TITLE
1P29 cannot be replaced (special scope)

### ISSUE THREAD

**Issue by indig0fox** [FridayNightFight/FNF#114]
https://discord.com/channels/106475368495484928/502655964521037857/888505882244169748

shouldn't be a special scope?
or is not detected at switch attempt

**Comment by tanaaKa** [comment]
![image](https://user-images.githubusercontent.com/9407533/133867412-0a0c4188-6495-4a6a-ba28-9e4dc0d4a718.png)

One of my members apparently got around this
