### ISSUE TITLE
CTF 1 way variance compliance

### ISSUE THREAD

**Issue by AdmiralGhoster** [FridayNightFight/FNF#115]
** issue:**
a change in the code from 2 months ago  in the transition from version 2.3.1 to 2.3.2 add a line of code to the "ctf_client.sqf " file that makes it so that the flag drop zone is shown to both side durring the map breif when the flag starts in the attackers (flag carriers) zone. this make it so that the defenders know where the zone is and can establish defenses that would turn the area into a fortress.

`if (playerside == phx_attackingSide || ctf_flagPole inArea _attackSpawnMark) then {`

*solution 1* 
revert the current line 58 of the ctf_client.sqf back to just having it not shown to defenders 
`if (playerside == phx_attackingSide) then {`
 
*solution 2 *
add a variable in the gamemodes ctf file (...\mode_config\cft.sqf) that booleans if the capture zone is shown to defenders

ctf.sqf line 4 `_showflagzone = false; // set to true to show the defenders where the zone is before attackers pick up the flag`
&
ctf_client.sqf line 58 `if (playerside == phx_attackingSide || _showflagzone) then {`

**Comment by Mjolnir64** [comment]
https://github.com/FridayNightFight/FNF/commit/60a76f566f248aa9cb220d8180ca6b46bbe93e7b
