### ISSUE TITLE
mission-based vehicle presets

### ISSUE THREAD

**Issue by indig0fox** [FridayNightFight/FNF#122]
Another thing I want to implement is a system where PLs can select from mission-maker defined 'presets' of vehicular and static assets. 
implementation wise my first thought is it have a second area marker than can be placed within safe start. the commander receives a menu of some kind that allows them to choose between 2 or 3 sets of vehicles. maybe a helo and two m1117s, 4 m113s, or a helo and minigun humvee. scroll wheel or ace menu. and once selected, it'll spawn those vehicles in the area marker and the menu will go away.

missionConfigFile for MMs to customize?

**Comment by Mallen-git** [comment]
would be a royal pain for balance imo, also i dont think company commanders would enjoy it
