### ISSUE TITLE
IntelIgent game end timer (Susstained assult)

### ISSUE THREAD

**Issue by AdmiralGhoster** [FridayNightFight/FNF#174]
Add the feature where the server on mission start, the server gets the real time and if the time over runs the event starts (2:30pm or 8pm), adjust the countdown to reflect it. 
it will also check to see if the the late/early start is greater then 1 hour but less then 2 (or however long sus runs for) and divides the remining time by 2 to allow for 2 equal length matches. 

The script should be able to handle a start of the susass missions to allow for any time start.

**
susass_Defualt_timelimit = 60 minutes;
Current_time = (get real time);
start_array = [14:30,20:00];

///scripting thing, i can write it out later but idea///
 if less then early start, calculate time (if (2hour>timeleft untill start >1hour) then evnely divide time left) else  if (time left < 1hour) set match time to time left.  ect....
 **

**Comment by Mallen-git** [comment]
This repo is currently only for the standard FNF Framework, SUSSASS is handeled exclusively by Banks on the FNF Discord atm!
