### ISSUE TITLE
Feature to allow spectators to mute other spectators in their channel and just hear alive player voices

### ISSUE THREAD

**Issue by martin7125** [FridayNightFight/FNF#29]
Also potentially add a whitelist functionality to allow a spectator to hear other specific spectators. Would be useful for casters and such to be able to talk to each other and hear player voices.

**Comment by indig0fox** [comment]
to test - set TFAR force spectator to OFF and see how it behaves while in ACE spectator (if it re-forces to spectator voice or other behavior)
likely not possible without recoding part of TFAR, this is functionality that's native in ACRE2

**Comment by Mallen-git** [comment]
i think this has been added and works but haven't tested it recently
