### ISSUE TITLE
Add an in-game menu for FNF staff members

### ISSUE THREAD

**Issue by martin7125** [FridayNightFight/FNF#30]
A first version should have the following features:

1. Kick players
2. Ban players

More features can be added over time.

**Comment by indig0fox** [comment]
@Mallen-git could you add a second button for BAN (and make it tiny or require a second confirmation step) to the existing admin menu in v3.0.31?
https://github.com/FridayNightFight/FNF/blob/v3.0.31/FNF_MissionTemplate.VR/client/misc/admin/adminKick/fn_adminKickUI.sqf
