### ISSUE TITLE
Create new unflip functionality

### ISSUE THREAD

**Issue by indig0fox** [FridayNightFight/FNF#32]
Create FNF-specific unflip function that allows players to reset vehicles to an upright position in-game through an Add Action (or change to space-action).

**Comment by indig0fox** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Technical Team 2021-06-xx](https://trello.com/c/OankOLxr/64-technical-team-2021-06-xx)

**Comment by Mallen-git** [comment]
nothing wrong with the current un-flip functionality, dont fix whats not broke atm
