### ISSUE TITLE
Add camera FOV change capability to ACE Spectator

### ISSUE THREAD

**Issue by indig0fox** [FridayNightFight/FNF#46]
If possible, add functionality to ACE Spectator that enables FOV scrolling for cinematic capture.

For reference, DTAS spectator view allows `Ctrl` + `Scroll Wheel` to change FOV of spectator cam.

**Comment by fauxhawkfox** [comment]
setAperture

**Comment by Mallen-git** [comment]
not needed, has not been requested since this issue was opened
